### PR TITLE
Remove round brackets in arrow function with one input

### PR DESCRIPTION
**Pull request by zackharley**
By removing the round brackets on arrow functions with one input we can improve readability.

### CODE REVIEW

**Comment by vsemozhetbyt** [comment]
It seems to be a matter of style taste. See, for example, this distinction in the very popular guide: https://github.com/airbnb/javascript#arrows--one-arg-parens

**Comment by ryanmcdermott** [comment]
Hey Zack! Thanks for looking into this issue and bringing your work.

As far as style choices, this is a tough thing. The problem is that these arguments always break down into something like a tabs vs. spaces debate, where there's no obvious winner. I've been approving _some_ readability changes, but almost only when it comes to stuff like inconsistencies in formatting between the rest of the document. If we start changing smaller style things then at some point in the future someone will come in and try to change it back. It's all personal preference at the end of the day!

Please feel free to send more of your PRs. This project has been drastically improved by great developers such as yourself!

**Comment by zackharley** [comment]
Thanks for the feedback Ryan! Great work on the whole project.

**Comment by ryanmcdermott** [comment]
Thank you Zack that means a lot!

**Pull request closed without merging**
