### PR TITLE
Open/Closed Principle (OCP) example change

### PR DESCRIPTION
**Pull request by Attrash-Islam**
Changed the mutation of data to be passed-in to the constructor

`Decoupled Dependency` best practices is to make sure that inputs are dynamically configured in initializing hook (out of the class scope).

Particularly in this example where HTTP methods are not commonly get changed it's prefered to configure outside the scope of the class

### CODE REVIEW

**Comment by Attrash-Islam** [comment]
This is a great explanation of the decoupled dependency:
https://blog.nrwl.io/essential-angular-dependency-injection-a6b9dcca1761#.pju7bx92s

**Comment by vsemozhetbyt** [comment]
Does it match with decoupled dependency to combine with defaults?
```js
class AjaxRequester {
  constructor(HTTP_METHODS = ['POST', 'PUT', 'GET']) {
    this.HTTP_METHODS = HTTP_METHODS;
  }

  get(url) {
    // ...
  }

}
```

**Comment by Attrash-Islam** [comment]
Yes. Because overriding them will still give the Open-Closed Principle (plug-able component)

**Comment by l20847688** [comment]
y

**Comment by Attrash-Islam** [comment]
Because I'm affected from the Angular way since working with Angular for the past four years :)
Also other ways are accepted

just to make the point clear to be adapted (as it fit here also)

**Comment by Attrash-Islam** [comment]
Okay. Let get this explained with excellent example. I'm building right now a plugin that is called infinite-autocomplete which will be built in TypeScript.

I want to design it as this:

```
Class InfiniteAutocomplete {

}

**Comment by Attrash-Islam** [comment]
This class contains two classes:

```
Class inputComponent implement IInputComponent {}
Class resultComponent implement IResultComponent {}
```

Now, open-closed principle stands for pluggable system, so my main component (InfiniteAutocomplete) will contains those two classes in the constructor as so:

```
Constructor (inputComp, resultsComp) {
 this.inputComp = new inputComp || default;
 this.resultComp = ...
}
```

But aside the syntax (not complete), but if anyone override those two classes then he'll change the whole plugin, but he must implement the same interfaces

**Comment by Attrash-Islam** [comment]
Thanks @Lacka90 :)

Unfortunately, my example above is written in TypeScript so I can't push it into this repository, but it's really apply to the OCP (Open-Closed principles) exactly as I saw in Robert Martin books! 

Thanks

**Comment by Attrash-Islam** [comment]
This is the real working code in TypeScript: 

https://github.com/Attrash-Islam/infinite-autocomplete/blob/master/src/Components/InfiniteAutocomplete.ts

Check Examples folder

**Comment by ryanmcdermott** [comment]
Hey @Attrash-Islam! Since your example deals more with TS, which I love, as opposed to JS, I'm going to close this for now. Now, a Clean Code TypeScript is something I would love to see 😉

**Comment by Attrash-Islam** [comment]
I'm waiting for that repo to be opended ;) and when you open it my pull request will be the first ;)

Thanks!

**Pull request closed without merging**
