### PR TITLE
Fix one code exsample use `console.log` to print error

### PR DESCRIPTION
**Pull request by othree**
Based on the **Error Handling** section.
I think good example should all use `console.error` to deal with error messages.

### CODE REVIEW

**Comment by vsemozhetbyt** [comment]
It seems the line [1798](https://github.com/othree/clean-code-javascript/blame/23e0da33799f3ec1c5d2367a5c32255ea91566fe/README.md#L1798) should be corrected as well.

**Comment by othree** [comment]
Line 1798 is bad example. Use `console.log` on purpose.

**Comment by vsemozhetbyt** [comment]
I mean the bad examples should not be bad in all respects. Compare this lines in the bad examples:

https://github.com/ryanmcdermott/clean-code-javascript/blame/master/README.md#L1708
https://github.com/ryanmcdermott/clean-code-javascript/blame/master/README.md#L1713
https://github.com/ryanmcdermott/clean-code-javascript/blame/master/README.md#L1756

**Comment by vsemozhetbyt** [comment]
Ah. sorry, I've misread this one.

**Comment by ryanmcdermott** [comment]
I love it!

**Pull request merged**
