### PR TITLE
Add remark about behaviour

### PR DESCRIPTION
**Pull request by schmijos**

### CODE REVIEW

**Comment by vsemozhetbyt** [comment]
Maybe 'falsy values ' would be a bit better? Maybe some link for conciseness (https://developer.mozilla.org/en-US/docs/Glossary/Falsy or http://speakingjs.com/es5/ch01.html#basic_truthy_falsy, for example).

**Comment by ryanmcdermott** [comment]
True, values other than `undefined` will not get overwritten by default arguments. Darn JavaScript's silly type system! The Bad and Good examples are not strictly the same, but people in general are using them to handle undefined `arguments`. If people are directly passing in `false`, `null`, etc. into a function then they will have a bad time. I think if other contributors here have a strong opinion about this we can include the caveat. If we do include the caveat, let's put this is a comment in the Good example and not a piece of bold text outside the code block. 

Thanks for putting this out here!

**Comment by schmijos** [comment]
I resolved the conflict and made an inline hint.

**Comment by ryanmcdermott** [comment]
Handled in 471371e4c7745612b6413ed56087b956daee22f0

Thanks for bringing this to everyone's attention! 😄

**Pull request closed without merging**
