### PR TITLE
Simplify "Use searchable names" example

### PR DESCRIPTION
**Pull request by mitogh**
There is no need to create an arrow function to execute a function inside of the timeout.

### CODE REVIEW

**Comment by vsemozhetbyt** [comment]
It is not always true. See, for example, [this explanation](http://speakingjs.com/es5/ch01.html#_extracting_methods).

Compare:
```js
const launcher = {
  bang: 'bang!',

  blastOff() {
    console.log(this.bang);
  },

  timer() {
    setTimeout(() => {
      this.blastOff();
    }, 100);
  },
};

launcher.timer();
```
```
bang!
```
```js
const launcher = {
  bang: 'bang!',

  blastOff() {
    console.log(this.bang);
  },

  timer() {
    setTimeout(this.blastOff, 100);
  },
};

launcher.timer();
```
```
undefined
```
```js
const launcher = {
  bang: 'bang!',

  blastOff() {
    console.log(this.bang);
  },

  timer() {
    setTimeout(this.blastOff.bind(this), 100);
  },
};

launcher.timer();
```
```
bang!
```
I don't know, though, what is better for readability — the first code or the third one. But the second code could be an erroneous replacement if the function uses a call context.

**Comment by mitogh** [comment]
I think that is most the way you define the callback `function` since `setTimeout` by definition expects a `function` as parameter  the current example uses an anonymous function to just execute this function without looking into the way you use it.

Since the example does not assume any specific scenario or in what context is used.

**Comment by vsemozhetbyt** [comment]
@mitogh Maybe then it would be better not to use `this` at all? `this` do assume some specific scenario or context.

**Comment by mitogh** [comment]
I think that might be the best scenario I guess @vsemozhetbyt

**Comment by ryanmcdermott** [comment]
Thanks Crisoforo!

**Comment by mitogh** [comment]
No problem man thank you!

**Pull request merged**
