### PR TITLE
Fixed typescript example

### PR DESCRIPTION
**Pull request by KendrickIW**
Fixed the example to show usage of typescript. Also that same example works if you want to promote the usage of Flow

### CODE REVIEW

**Comment by styfle** [comment]
Should you change the language of the snippet?

```md
    ```javascript
    function wrong() { }
    ```
```

```md
    ```typescript
    function fixed() { }
    ```
```

**Comment by ryanmcdermott** [comment]
Hey there! I've gone back and forth about this. Should this show TypeScript code at all? Since this is focused just on JavaScript I would prefer to keep it solely JavaScript. The subsection in question is regarding the avoidance of runtime type checks in JS, and advocates using a typed alternative. Is the advocacy enough? I welcome comments :)

**Comment by styfle** [comment]
This is the description before the code snippet.

> If you are working with basic primitive values like strings, integers, and arrays, and you can't use polymorphism but you still feel the need to type-check, you should consider using TypeScript. It is an excellent alternative to normal JavaScript, as it provides you with static typing on top of standard JavaScript syntax. The problem with manually type-checking normal JavaScript is that doing it well requires so much extra verbiage that the faux "type-safety" you get doesn't make up for the lost readability. Keep your JavaScript clean, write good tests, and have good code reviews. Otherwise, do all of that but with TypeScript (which, like I said, is a great alternative!).

It seems like the best way to show the "bad" and "good" is to show how to convert a run-time type check to a compile-time type check. Maybe you could add a link to the [TypeScript Playground](https://www.typescriptlang.org/play/#src=function%20combine(val1%3A%20number%2C%20val2%3A%20number)%20%7B%0D%0A%20%20return%20val1%20%2B%20val2%3B%0D%0A%7D%0D%0A%0D%0Acombine(3%2C%204)%3B%20%20%2F%2F%20ok%0D%0Acombine(3%2C%20'f')%3B%2F%2F%20error) so it's a little easier to see why this is valuable.

**Comment by styfle** [comment]
And now that I look at the original JS code, I think this is not easily type checked using TypeScript since it requires both types to be the same.

You could add a `.d.ts` and overload the method with (string, string) or (number, number). Maybe we can come up with a better "bad" example that can be corrected with typescript?

**Comment by KendrickIW** [comment]
To me the subsection suggested that the good was going to be an example of TypeScript. What if there was another `good` example that says the typescript way?

**Comment by KendrickIW** [comment]
@styfle 

> Should you change the language of the snippet?

I wasn't aware there was support for for typescript. I can change that

**Comment by ryanmcdermott** [comment]
Every subsection should have just one `Bad` and one `Good` example.

I'm totally open to hearing a convincing argument, but as it is I'm not too sure about including another language in an example other than simply saying "go check this superset of JS if you want type-checking"

**Comment by felquis** [comment]
https://github.com/ryanmcdermott/clean-code-javascript/pull/221#issuecomment-308851112 that being said, we should close this PR! Right?

**Comment by ryanmcdermott** [comment]
Looks like there's now a TypeScript clean code project, see here: https://github.com/labs42io/clean-code-typescript

**Pull request closed without merging**
