### PR TITLE
Added optional chaining

### PR DESCRIPTION
**Pull request by uxitten**
I added this sample:

**Bad:**
```javascript
const name = user && user.profile && user.profile.name;
```
**Good:**
```javascript
const name = user?.profile?.name;
```

### CODE REVIEW

**Comment by ryanmcdermott** [comment]
I'm a bit hesitant to introduce new concepts that aren't in the Clean Code book. I don't want to make this project about "use this cool new JS feature". If we did that, this would grow indefinitely. 

Can you find an example in Clean Code where optional chaining is discussed?

**Comment by uxitten** [comment]
I agree, but I think this feature can help to write better code. We want to suggest to all developers to write better code, sometimes we have use new feature to write better code ex:

```javascript
try {
 // code 1
} catch (e) {
 // nothing, but we have a force to write this segment
}
// code 2

// so now we can write better than

try {
 // code 1
} finally {
 // code 2
}
```

**Comment by ryanmcdermott** [comment]
I liked you numeric separator PR because it wasn't about that feature explicitly, it was about constants which Clean Code covers! If the book doesn't cover a concept I really don't want to introduce it. I've done it a couple of times herein, and it's set an unfortunate precedent I don't want to continue.

**Comment by uxitten** [comment]
All right man 👌🏻

**Comment by uxitten** [comment]
Ryan, I want to close this, are you agree?

**Comment by lsaadeh** [comment]
I agree that we won't want to include examples that aren't the book, but in saying that people come to this github to learn how to write the best code. Excluding optional chain wouldn't be in the best interest of the users which should be the priority. Maybe we can include this example but explicitly say that its not in the book?

**Comment by ryanmcdermott** [comment]
Let's close this! I'm just anxious about setting a precedent that would cause this project to become voluminous with non-Clean Code concepts.

**Pull request closed without merging**
