### PR TITLE
Call for discussion about "Remove duplicate code"

### PR DESCRIPTION
**Pull request by d4rkr00t**
Hi,

Thank you for awesome work you've done here.

Some ideas on "Remove duplicate code" which might be useful for somebody.

### First of all, duplicating code isn't that bad :).

Great blog post covers this topic — [The Wrong Abstraction](https://www.sandimetz.com/blog/2016/1/20/the-wrong-abstraction).
And the best quotes from that article state:

> duplication is far cheaper than the wrong abstraction

And:

> prefer duplication over the wrong abstraction

Most of the experienced devs to whom I showed this article were agree with it.
Therefore it's a bit too categoricall to say:

> Never ever, ever, under any circumstance, have duplicate code. There's no reason for it and it's quite possibly the worst sin you can commit as a professional developer.

It, in my opinion, might mislead begginers to belive that duplicate code is pure evil which will end up
in abstraction mess and in even less maintanable code.

#### The reasons why I think it's better:

1. You can easilly remove any of those functions without changing other one.
2. They are easier to test.
3. They are easier to maintain and extend.

#### Why I don't like good example:

First of all, after refactoring we have different result for developer:

```js
function showList(employees) {
  employees.forEach(employee => {
    // ...

    const data = {
      expectedSalary: expectedSalary,
      experience: experience,
      portfolio: portfolio // used to return "githubLink" for developer
    };

    // ...
  });
}
```

So, if we want to keep contract of our functions as it was before refactoring we will have to do something like this (approximately):

```js
function showList(employees) {
  employees.forEach(employee => {
    const expectedSalary = employee.calculateExpectedSalary();
    const experience = employee.getExperience();
    const data = {
      expectedSalary: expectedSalary,
      experience: experience
    };

    if (employee.type === 'manager') {
      data.portfolio = employee.getMBAProjects();
    } else {
      data.githubLink = employee.getGithubLink();
    }

    render(data);
  });
}
```

But we still have that ugly `if` condition.
By introducing `if` here we define a place for futher comming additional logic and conditions.
Until, eventually, code becomes incomprehensible.

### What we can do if we still want to refactor these functions?

```javascript
// Extracting common data from employee

function getCommonEmployeeData(employee) {
  const expectedSalary = developer.calculateExpectedSalary();
  const experience = developer.getExperience();

  return {
    expectedSalary: expectedSalary,
    experience: experience,
  };
}

// Specific things live in separate functions

function showDeveloperList(developers) {
  developers.forEach(developer => {
    const data = getCommonEmployeeData(developer);
    data.githubLink = developer.getGithubLink();

    render(data);
  });
}

function showManagerList(managers) {
  managers.forEach(manager => {
    const data = getCommonEmployeeData(developer);
    data.portfolio = manager.getMBAProjects();

    render(data);
  });
}
```

1. By doing this we got rid of unnecessary condition in our code.
2. It's now easier to extend or add new type of employee, hence we don't need to test not affected types.
3. It's easier to write unit tests.
4. We are following the single responsibility rule, hence each our functions is dedicated to specific type of employee and has no idea about other types.

What do you think?

### CODE REVIEW

**Comment by ryanmcdermott** [comment]
Hey there Stanislav! Your point is definitely true, that when you have to choose between duplicate code and a bad abstraction, you should probably choose duplicate code. BUT, for picking the right abstraction that's what the SOLID principles . So in other words, you should never end up in the case where you have to choose between two evils 😄 

As for the Bad/Good code examples for this duplicate code subsection, they are a bit contrived I admit, and so the distinction between Bad and Good may seem silly, unrealistic, or not even clear. In the latter case, let's fix the clarity. 

I think your fix gets closer to getting this to be a better example. It's almost there! Maybe we should rethink this example altogether and go with something where there's an obvious benefit of the Good over the Bad. What do you think?

**Comment by d4rkr00t** [comment]
Hi, sorry for late response, have been moving in to new place. 

Yeah, sounds great, I'll try to come up with better example :)

**Comment by ryanmcdermott** [comment]
Awesome! Best of luck on your move 😄

**Comment by felquis** [comment]
This is a really good example.

**Comment by ryanmcdermott** [comment]
Closing due to inactivity, feel free to re-open!

**Pull request closed without merging**
