### PR TITLE
Fixed few examples

### PR DESCRIPTION
**Pull request by HemantPawar**
Fixed few lines by adding missing semicolons.

### CODE REVIEW

**Comment by vsemozhetbyt** [comment]
It seems there are some more on these lines:

123
```javascript
const match = cityStateRegex.match(cityStateRegex) // < HERE
```

209
```javascript
  var breweryName = name || 'Hipster Brew Co.' // < HERE
```

245
```javascript
var menuConfig = {
  title: 'Foo',
  body: 'Bar',
  buttonText: 'Baz',
  cancellable: true
} // < HERE
```

482
```javascript
var menuConfig = {
  title: null,
  body: 'Bar',
  buttonText: null,
  cancellable: true
} // < HERE
```

502
```javascript
var menuConfig = {
  title: 'Order',
  // User did not include 'body' key
  buttonText: 'Send',
  cancellable: true
} // < HERE
```

584
```javascript
var name = 'Ryan McDermott' // < HERE
```

982
```javascript
var Employee = function(name) {
  this.name = name;
} // < HERE
```

986
```javascript
Employee.prototype.getName = function() {
  return this.name;
} // < HERE
```

1735 + 1737
```javascript
require('request').get('https://en.wikipedia.org/wiki/Robert_Cecil_Martin', function(err, response) {
  if (err) {
    console.error(err);
  }
  else {
    require('fs').writeFile('article.html', response.body, function(err) {
      if (err) {
        console.error(err);
      } else {
        console.log('File written');
      }
    }) // < HERE
  }
}) // < HERE
```

1752
```javascript
require('request-promise').get('https://en.wikipedia.org/wiki/Robert_Cecil_Martin')
  .then(function(response) {
    return require('fs-promise').writeFile('article.html', response);
  })
  .then(function() {
    console.log('File written');
  })
  .catch(function(err) {
    console.error(err);
  }) // < HERE
```

1775
```javascript
require('request-promise').get('https://en.wikipedia.org/wiki/Robert_Cecil_Martin')
  .then(function(response) {
    return require('fs-promise').writeFile('article.html', response);
  })
  .then(function() {
    console.log('File written');
  })
  .catch(function(err) {
    console.error(err);
  }) // < HERE
```

1783
```javascript
    var request = await require('request-promise') // < HERE
```

2107
```javascript
let actions = function() {
  // ...
} // < HERE
```

2119
```javascript
let actions = function() {
  // ...
} // < HERE
```

**Comment by HemantPawar** [comment]
@vsemozhetbyt Great catch!!! I have added above changes.

**Comment by ryanmcdermott** [comment]
Awesome finds! Can you rebase this with master and resolve conflicts? There was a large change after #51 which has affected this branch a little bit. Thank you!

**Comment by HemantPawar** [comment]
@ryanmcdermott done :)

**Comment by vsemozhetbyt** [comment]
@HemantPawar Just found one more :) Line 597:
```js
Array.prototype.diff = function(comparisonArray) {
  const values = [];
  const hash = {};

  for (let i of comparisonArray) {
    hash[i] = true;
  }

  for (let i of this) {
    if (!hash[i]) {
      values.push(i);
    }
  }

  return values;
} // < HERE
```

**Comment by vsemozhetbyt** [comment]
And the line 1514:
```js
car.setModel('F-150') // < HERE
```

**Comment by AAAoooo** [comment]
car.setModel('F-150') // < HERE

**Comment by HemantPawar** [comment]
Thanks @vsemozhetbyt :)

**Comment by HemantPawar** [comment]
@ryanmcdermott resolved conflicts

**Comment by ryanmcdermott** [comment]
Thanks Hemant! While these changes may feel small, they go such a long way to improving the readability of this project 😄

**Pull request merged**
