### PR TITLE
[section] Avoid negative conditionals

### PR DESCRIPTION
**Pull request by lnfnunes**
- Added a simple section description
- Added a second case example where negative conditionals are a good choice.

### CODE REVIEW

**Comment by ryanmcdermott** [comment]
Hey there! Can we remove the second example? Or can we consolidate it into the first example? I'm keeping each subsection with only one Bad example and one Good example.

**Comment by lnfnunes** [comment]
Hi @ryanmcdermott, please could you check if that's fine now.

**Comment by DannyFeliz** [comment]
Ping @ryanmcdermott 👀

**Comment by ryanmcdermott** [comment]
Closing due to inactivity, feel free to re-open!

**Pull request closed without merging**
