### PR TITLE
added spanish translation

### PR DESCRIPTION
**Pull request by andersontr15**
currently translating it all to spanish.

### CODE REVIEW

**Comment by andersontr15** [comment]
can i get confirmation that my translation will be approved and added to the translation section once completed?

**Comment by ryanmcdermott** [comment]
It would be ideal if it's complete :smile:  What is the state of it now @andersontr15?

**Comment by andersontr15** [comment]
Awesome. It's about 65-70% done translation wise. I'd like to translate the code examples as well but I'll let you know when the actual text is done.

**Comment by andersontr15** [comment]
@ryanmcdermott translation is now 100%. Still will continue changing out some of the code examples to Spanish, but the full text is translated.

**Comment by ryanmcdermott** [comment]
Great job! 🎉 I appreciate your contribution!

**Comment by hienvd** [comment]
Excuse me, I wonder why you use Uruguay flag for Spanish translation? @andersontr15

**Comment by andersontr15** [comment]
@hienvd Why not? Beautiful country.

**Pull request merged**
