### PR TITLE
translate to chinese.

### PR DESCRIPTION
**Pull request by beginor**
translate to chinese.

### CODE REVIEW

**Comment by beginor** [comment]
@appleboy I kept the english version because I think there might be some better translations, and I am not sure my translation is ok.

**Comment by appleboy** [comment]
@beginor You will remove the English version if everything is ok. Right?

**Comment by beginor** [comment]
@appleboy Yes, I will remove the English version later.

**Comment by ryanmcdermott** [comment]
Thanks for taking the time on this! Can you open up a different PR where you include a link to your fork? Take a look at the _Translation_ section for how to do this. Thanks!

**Comment by beginor** [comment]
OK

**Pull request closed without merging**
