### PR TITLE
Remove unnecessary line in isClientActive function

### PR DESCRIPTION
**Pull request by ihorskyi**
Line was likely copied by mistake

### CODE REVIEW

**Comment by vsemozhetbyt** [comment]
Why do you think it is unnecessary? Without this line, `clientRecord` is `undefined` and `client` is not used.

**Comment by ihorskyi** [comment]
@vsemozhetbyt I've just renamed it, should make more sense now

**Comment by JakoD** [comment]
`client` in this case is only your key (likely an email address) to look up the actual `clientRecord`, which holds all the other data. And that key won't have a method `isActive()`.

**Comment by ryanmcdermott** [comment]
Hey Ihor! As others are saying, `client` is just an ID to look up in the database. Theoretically if we remove the lookup call as in your PR we could also remove the other line and just have a stub function with `// ...`

I'm open to a discussion around cutting out verbiage in functions that really don't actually do anything. I was trying to strike a balance between totally contrived examples and some real production-looking code! In most cases though, they are kind of contrived. In this case, it's more of a production-looking fragment.

I'll close this PR, but if you would like to expand this to talk about clearing out 'fake code' from functions, that could be fun!

**Pull request closed without merging**
