### PR TITLE
Replace var with const

### PR DESCRIPTION
**Pull request by imranbaloch**

### CODE REVIEW

**Comment by vsemozhetbyt** [comment]
Please, check other PRs, there are some for this type of issues.

**Comment by leek** [comment]
Similar to (but not exactly the same as) #33.

**Comment by vsemozhetbyt** [comment]
https://github.com/ryanmcdermott/clean-code-javascript/pull/38 includes the same fragment as well.

**Comment by ryanmcdermott** [comment]
Thanks for taking the time @imranbaloch to do this! I am going to go with the PR below, but if you see anything on that one that needs to be fixed I would love to have your contributions:

https://github.com/ryanmcdermott/clean-code-javascript/pull/51

**Pull request closed without merging**
