### PR TITLE
Fill missing commas

### PR DESCRIPTION
**Pull request by iamken1204**

### CODE REVIEW

**Comment by Tarabass** [comment]
I think you meant to say semicolons or semi-colons ;)

I have an other point of view. Remove them all when you don't need them (like in for loops).

**Comment by iamken1204** [comment]
Always confused with commas and semicolons :(
IMO semicolons are not necessary for javascript (except `;(function(){})();`)

**Comment by ryanmcdermott** [comment]
Thanks for looking at this Kettan! Can you rebase this with master? I will merge in afterwards.

**Comment by ryanmcdermott** [comment]
Thanks Kettan!

**Pull request merged**
