### PR TITLE
Fix for #245 - Redundant information in `dont-add-unneeded-context`

### PR DESCRIPTION
**Pull request by GMaiolo**

### CODE REVIEW

**Comment by GMaiolo** [comment]
@toddmantell https://github.com/ryanmcdermott/clean-code-javascript/issues/245 is open for discussion, I just left the PR open in case it's needed to close it.

**Comment by jasp402** [comment]
I think that this is more a philosophical precept than a technicalism. Let's see the following example. suppose we have 3 objects. (table, car and house).

Now in real life I have a paint gun that works for all 3 things. I can paint any of the objects with the same tool.

but in this case the clean code tells me that I must necessarily have a paint gun for each object even if they are the same.

I can or use a single function for everything, passing the parameter (object, color).
or I can use one for each and internally each function has the color.

I believe that the clean code is not focused on simplifying the code but on clarifying it. so that if we follow the rules of clearCode. we must predispose our senses to write things that we do not think are good practices.

because 1 single function is more effective, scalable and maintainable. that "n" functions.

then at this point it becomes counter-productive and you have to choose between something readable. and something productive.


`const table = {
    color       : 'light',
    size        : '90x180'
};
const home = {
    bedrooms    : 3,
    bathrooms   : 1,
    garage      : 'Yes',
  	color		: 'turquoise'
};
const Car = {
    make        : 'Honda', 
    model       : 'Accord',
    color       : 'Blue'
};

function paintCar(car) {	
car.color = 'Red';
}
function paintHome(home) {	
home.color = 'Red';
}
function paintTable(table) {	
table.color = 'Red';
}
paintCar(Car)
paintHome(home)
paintTable(table)

console.log(Car)
console.log(home)
console.log(table)`

**Comment by toddmantell** [comment]
@jasp402 	I feel I didn't entirely address your point.  I totally agree that if you have a more general function that paints multiple different kinds of objects (like `paint(something)`), it would be excess duplication to have `paintHouse`, `paintCar`, etc. and I think you would want a general `paint` function to avoid unnecessary duplication.  What I was merely objecting to was the idea that one should mix the function name with the parameter name, like `paint(car)` in the function signature instead of `paintCar`.

**Comment by ryanmcdermott** [comment]
Closing this as `paint` isn't generic here, just a dummy example of course but it was focused more on the object property than the method name :)

**Pull request closed without merging**
