### PR TITLE
Spanish

### PR DESCRIPTION
**Pull request by faustinoloeza**

### CODE REVIEW

**Comment by felquis** [comment]
What?

**Comment by faustinoloeza** [comment]
What I have to do?

**Comment by felquis** [comment]
@ryanmcdermott who is  the project owner will may merge your Pull Request in the coming days.

Just wait :D

**Comment by faustinoloeza** [comment]
Thanks!!

**Comment by ryanmcdermott** [comment]
Can you make your second Spanish entry and the first Spanish entry into bullet points, in the same way that the Chinese entries are? Thanks!

**Comment by felquis** [comment]
If you are in your laptop do it for him please!

**Pull request closed without merging**
