### PR TITLE
Mistake in the "Make objects have private members" section.

### PR DESCRIPTION
**Pull request by kantuni**

### CODE REVIEW

**Comment by vsemozhetbyt** [comment]
These names are usually used for debugging, so there will be less anonymous functions in the stack trace.

**Comment by kantuni** [comment]
I didn't know you can do this:

```javascript
let a = function b() {
};
```
Thanks

**Comment by vsemozhetbyt** [comment]
This can be inferred sometime though: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

**Comment by kantuni** [comment]
Спасибо

**Pull request closed without merging**
