### PR TITLE
Add translations section + fix minor typo md error

### PR DESCRIPTION
**Pull request by fesnt**
Add translation section in the same format of AirBnb style, with Brazilian Portuguese and Chinese translations.

I"m unable to tell the difference between "Traditional" and "Simplified" Chinese as AirBnb did in their translations, perhaps someone can help with this distinction.

Also, fix a minor markdown error.

### CODE REVIEW

**Comment by ryanmcdermott** [comment]
Thank you so much for taking the time to put your translation together, and for this PR 🎉 Clean JavaScript for everyone!

**Comment by ryanmcdermott** [comment]
@fesnt Can you also include a link in your translation to this repository? Thank you!

**Comment by fesnt** [comment]
Yes, do you have a preference in the format I should do this, and where?

Also, people are opening issues with suggestions in the Portuguese translation. Some are fixes, but others are suggestions, for example: don't use `foreach`, only `map`. Should I keep opening issues here with the observations and fixes made this people?

**Comment by fesnt** [comment]
@ryanmcdermott, forgot to mark you on this, what are your thoughts on what I said before?

**Comment by ryanmcdermott** [comment]
I think we will start to diverge at a certain point if we don't keep connected on issues. Keep opening them here if you get different ones from this project! I don't have a preference for the link back to this repo! Anywhere you see fit, in any format. As long as there's a link 😄

**Pull request merged**
