### PR TITLE
Use const instead of var

### PR DESCRIPTION
**Pull request by wordofchristian**
This example should follow the guidelines about `const` vs `var` mentioned earlier

### CODE REVIEW

**Comment by amcclain** [comment]
Except for those pesky leap years... 😉  Then there's also the consideration that this snippet would go and call that cron half a million+ times, immediately... 

Maybe another example would be a bit more realistic?  To throw something out there...

```
const SLOW_QUERY_LIMIT = 15000;
...
const startTime = Date.now();
...
if ((Date.now() - startTime) > SLOW_QUERY_LIMIT) {
  logSlowQuery();
}
```

**Comment by ryanmcdermott** [comment]
Hey! I like that second commit you have that changes the example. The more fun we can make this, let's do it! This can be a dry topic for some people, so I appreciate your creativity. There will be merge conflicts with the PR below, so can you remove your change to var/const?

Thanks!
Thanks for taking the time @imranbaloch to do this! I am going to go with the PR below, but if you see anything on that one that needs to be fixed I would love to have your contributions:

#51

**Comment by amcclain** [comment]
Anyone who things this is a dry topic is in the wrong repo! 😄  

(But very much yes, agree wholeheartedly on "more fun," and very cool to see crowd-sourced clean code in action.  Thanks much for putting this out there.)

**Comment by wordofchristian** [comment]
Conflicts fixed

**Comment by ryanmcdermott** [comment]
Excellent, thank you Christian! It's a livelier example now.

**Pull request merged**
