### PR TITLE
Improve example "Function names should say what they do"

### PR DESCRIPTION
**Pull request by Tarabass**
Improve example to be more consistent and remove unneeded context

### CODE REVIEW

**Comment by Tarabass** [comment]
I created two commits. One without and one with prototype example. I would choose for the example with prototype, but leave it up to you (if you accept this pr).

**Comment by vsemozhetbyt** [comment]
Would the second commit contradict the [Don't write to global functions](https://github.com/ryanmcdermott/clean-code-javascript#dont-write-to-global-functions)?

**Comment by Tarabass** [comment]
Good point! Maybe the first commit is the winner then. Or the native Date object should be replaced with an "own object"?

**Comment by ryanmcdermott** [comment]
Agreed with @vsemozhetbyt. Let's not write to global functions :) I like your first commit though, can you remove that commit from this branch?

**Comment by Tarabass** [comment]
Reverted commit with prototype :)

**Comment by sylvainpolletvillard** [comment]
:+1: for this change.

* Functions should start by a verb to differenciate infinitive and simple past
example: `var dateSet = setDate()`

* Function names should indicate the argument order
example: `function addMonthToDate(month, date)`

**Comment by ryanmcdermott** [comment]
Thanks that's a great improvement!

**Pull request merged**
