### PR TITLE
update "remove duplicate code" to use ternary and ES6 harmony

### PR DESCRIPTION
**Pull request by churchie317**
A few things jump out at me here:

- My personal opinion is that the ternary operator is a good way to clean code up. It prevents littering code with unnecessary `if` statements and, in this case, it prevents having to write `portfolio =` twice. Some might say the ternary operator is a little more clever than clear, but my opinion is the simplicity gains far outweigh the loss in clarity. If you agree, it's probably worth giving the operator its own heading.

- I noticed your link to an Eric Elliott article earlier. I agree with him that ES6 should be used when possible. 

- I want to keep this PR atomic, but I think some clarity can be derived by cleaning up the object.

I think this is an awesome idea and wonderful contribution to the community! Thanks!

### CODE REVIEW

**Comment by schoenwaldnils** [comment]
I personally don't like the `?:` method.
At least if it doesn't fit in one single line.

How about this: 
```
let portfolio = employee.getGithubLink();

if (employee.type === 'manager') {
  portfolio = employee.getMBAProjects();
}
```

**Comment by churchie317** [comment]
Hm, I do see your point. 

However, I do think I'm still partial to the ternary operator because it's up-front and honest about its assignment. It says, 'This value can be one of two things. Whatever gets assigned to it first will be its value.' It's not immediately obvious in your proposal that portfolio may later be overwritten by another value. It also allows for the use of `const` here, which I believe should be used whenever possible.

That said, I do see the elegance in your proposal and wouldn't be surprised if the community ultimately settled on it.

**Comment by schoenwaldnils** [comment]
I also like to use `const` more. But there is also nothing bad in using `let`.

In this case using `let` indeed makes it kind of obvious that portfolio may later be overwritten by another value.
(Also the reassignment is just 3 lines below. What makes it pretty easy to find ^^)

And if you use linting right, the linter would error, if the variable isn't overwritten.

**Comment by churchie317** [comment]
True. 

I'm just envisioning a scenario where 1) someone doesn't make the intuitive leap that `let` is meant to be overwritten and 2) where the variable doesn't immediately get reassigned. Like, I can imagine the case where the reassignment--for one reason or another--isn't 3 lines below, but dozens.

Again, not married to my solution; if anything I'm coming around to you. Just trying to play the Devil's Advocate here.

**Comment by schoenwaldnils** [comment]
Anyone who use the ES6 `const` and `let` variables should know that `let` can (and should) be overridden. Otherwise you should use `const`. If the community can agree on this, there should be no problem to see that `let` gets overridden.

I can imaging the case that someone declares all variables at the top of the function, and override the let a few more lines below. But even then, the function seems to be already to big ;)

Playing the Devil's Advocate is the best way to eliminate possible error-cases. 
So, no problem with that ^^

**Comment by churchie317** [comment]
closing for now 👍

**Pull request closed without merging**
