### PR TITLE
Fixed a small typo

### PR DESCRIPTION
**Pull request by Risto-Mcintosh**

### CODE REVIEW

**Comment by jljorgenson18** [comment]
I don't think this is a typo. It's skipping the zero index value when destructuring because the first value matches the whole phrase "Cupertino 95014" instead of just the city or just the zip.

**Comment by ryanmcdermott** [comment]
If this feels like a typo then you're right! It's not readable enough. Maybe we should use an `_` character to denote it is not used, much like Python and other languages do.

**Comment by Risto-Mcintosh** [comment]
Ah I see. I think an `_` would be more readable

**Comment by ryanmcdermott** [comment]
Thanks that looks great!

**Pull request merged**
