### PR TITLE
consistent variable names in definition as well as function argument

### PR DESCRIPTION
**Pull request by dmytro-kerest**
Found the inconsistencies in the example in variable definition and functionaargument

### CODE REVIEW

**Comment by vsemozhetbyt** [comment]
This was changed intentionally in https://github.com/ryanmcdermott/clean-code-javascript/pull/97.

**Comment by ryanmcdermott** [comment]
@vsemozhetbyt Should we change this back? This seems to be getting a steady stream of PRs trying to change it to its original form.

**Comment by vsemozhetbyt** [comment]
@ryanmcdermott Yeah, there are five ones at least according to references in the #97. I see three possible fixes:
1. Add a function call after the variable and function declaration. However, this could reduce confusion not enough.
2. Delete the variable declaration. Add a function call after the function declaration with object literal as an argument. This could be less readable.
3. Revert the fix and return the shadowing. This could be confusing for other users an could teach questionable naming scheme.

Please, do whatever you think is more preferable.

**Comment by vsemozhetbyt** [comment]
Also, we can make both names more different: `config` and `option`, for example. But this can slightly contradict the ['Use the same vocabulary for the same type of variable'](https://github.com/ryanmcdermott/clean-code-javascript#use-the-same-vocabulary-for-the-same-type-of-variable) part.

**Comment by ryanmcdermott** [comment]
I think the only halfway decent choice is option 2! It's not perfect in terms of readability, but it will prevent people from doing two other worse things which are variable shadowing and trying to change this back.

**Comment by vsemozhetbyt** [comment]
[Hopefully done)](https://github.com/ryanmcdermott/clean-code-javascript/pull/153)

**Pull request closed without merging**
