### PR TITLE
Add New Topic

### PR DESCRIPTION
**Pull request by iChwn**
-Ternary if-else operation

### CODE REVIEW

**Comment by ryanmcdermott** [comment]
I can't compare a diff here, can you keep the formatting the same and just add the new lines? It looks like this changed all 5600 lines of the README. Thanks!

**Comment by iChwn** [comment]
okay ill make a new line

Pada tanggal Kam, 3 Okt 2019 pukul 11.57 Ryan McDermott <
notifications@github.com> menulis:

**Comment by iChwn** [comment]
@ryanmcdermott i've been changing the new Topic on the new line :)

**Comment by rudotriton** [comment]
You'd need to adjust some things about your changes to make it a valid contribution: the spelling, punctuation and grammar need to be fixed, the markdown is not formatted consistently and the code inside the blocks also needs a consistent formatting. Besides, why not a switch statement instead of an if-else?

**Comment by ryanmcdermott** [comment]
Going to close this PR as it doesn't reflect any direct advice I can find in the Clean Code book. Feel free to open another at anytime! Thanks for your help!

**Pull request closed without merging**
